In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [8]:
# Make sure 'california_housing_train.csv' is uploaded to your Colab environment or replace 'california_housing_train.csv' with the correct path to your Excel file.
dataset=pd.read_csv('california_housing_train.csv')
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values
print(X)
print(Y)

[[-114.31     34.19     15.     ... 1015.      472.        1.4936]
 [-114.47     34.4      19.     ... 1129.      463.        1.82  ]
 [-114.56     33.69     17.     ...  333.      117.        1.6509]
 ...
 [-124.3      41.84     17.     ... 1244.      456.        3.0313]
 [-124.3      41.8      19.     ... 1298.      478.        1.9797]
 [-124.35     40.54     52.     ...  806.      270.        3.0147]]
[ 66900.  80100.  85700. ... 103600.  85800.  94600.]


In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=0)

In [ ]:
ann=tf.keras.models.Sequential()

In [ ]:
ann.add(tf.keras.layers.Dense(units=3,activation='relu'))
ann.add(tf.keras.layers.Dense(units=3,activation='relu'))
ann.add(tf.keras.layers.Dense(units=3,activation='relu'))
ann.add(tf.keras.layers.Dense(units=1))


In [ ]:
ann.compile(optimizer='adam', loss='mean_squared_error')

In [ ]:
ann.fit(X_train,Y_train,batch_size=64,epochs=100)